ingress:
  hostname: mygreendays.de

frontend:
  containerPort: 8080
  service:
    type: ClusterIP
    port: 80
  image:
    name: ""
    pullPolicy: IfNotPresent

# backend:
#   DatabaseHost: "artemis-postgresql.artemis-prod.svc.cluster.local"

keycloak:
  ingress:
    hostname: auth.mygreendays.de
    extraTls:
      - hosts:
          # Make sure its same as ingress.hostname
          - auth.mygreendays.de
        secretName: keycloak-tls
