FROM docker.io/node:20.18.0 as builder

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . /usr/src/app

ARG PWA_ICON_GENERATE_COMMAND

ARG STAGE

RUN npm install

RUN npm rebuild --verbose sharp

RUN echo "PWA_ICON_GENERATE_COMMAND: $PWA_ICON_GENERATE_COMMAND"

RUN npm run $PWA_ICON_GENERATE_COMMAND

RUN npm run build -- --mode $STAGE

FROM registry.access.redhat.com/rhscl/httpd-24-rhel7
COPY --from=builder /usr/src/app/dist /var/www/html/
COPY ./httpd.conf /etc/httpd/conf.d/meat.conf