kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.keycloak.postgresql.primary.persistence.existingClaim }}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi