services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: artemis
    volumes:
      - pgdata:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./realms:/opt/keycloak/data/import
    ports:
      - 8080:8080
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - VIRTUAL_PORT=8080
      - KC_HOSTNAME=keycloak
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc-db/postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=changeme
  kc-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PASSWORD=changeme
    volumes:
      - keycloak_db:/var/lib/postgresql/data
volumes:
  pgdata:
  keycloak_db: