apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "artemis.name" . }}
  labels:
    {{- include "artemis.backend.labels" . | nindent 4 }}
  annotations: {}
    #route.openshift.io/termination: edge
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "artemis.backend.name" . }}
                port:
                  name: "http"
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "artemis.frontend.name" . }}
                port:
                  name: "http"