services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: artemis
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: