apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.backend.name" . }}
  labels:
    {{- include "artemis.backend.labels" . | nindent 4 }}
data:
    LOG_LEVEL: {{ .Values.backend.log_level | quote }}
    DATABASE_HOST: {{ .Values.backend.DatabaseHost | quote }}
    DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
    DATABASE_NAME: {{ .Values.postgresql.auth.database | quote }}
    DATABASE_PORT: {{ .Values.backend.DatabasePort | quote }}
    KEYCLOAK_CLIENT_ID: {{ .Values.backend.KeycloakClientID | quote }}
    KEYCLOAK_REALM: {{ .Values.backend.KeycloakRealm | quote }}
    KEYCLOAK_REALM_ISSUER_URL: https://{{ .Values.keycloak.ingress.hostname }}/realms/{{ .Values.backend.KeycloakRealm }}
    KEYCLOAK_REALM_REDIRECT_URI: https://{{ .Values.ingress.hostname }}{{ .Values.backend.KeycloakRealmRedirectPath }}
    KEYCLOAK_URL: https://{{ .Values.keycloak.ingress.hostname }}
    FRONTEND_ORIGIN: https://{{ .Values.ingress.hostname }}
